/**
 * Integrity tests for the generated shell-plugins dataset.
 *
 * `data/shell-plugins.json` is machine-generated by `scripts/update-1p-shell-plugins.ts`
 * from the upstream `1Password/shell-plugins` repo, and lands via an automated weekly
 * PR. Nothing else in the suite can see it: `loadCuratedPlugins()` reads the file at
 * runtime inside a `catch` that returns `[]`, so a gutted or malformed list degrades
 * silently — the onboarding picker simply offers nothing, and lint/typecheck/unit
 * tests all stay green.
 *
 * These tests are therefore the *only* CI gate standing between a bad upstream parse
 * and a published package. They intentionally assert on the committed data itself
 * rather than on parser internals, because the failure mode that matters is "the JSON
 * that ships is wrong", regardless of which part of the pipeline produced it.
 */

import { readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";

interface CuratedPlugin {
  name: string;
  slug: string;
  envVars: string[];
  primaryEnvVar: string | null;
  pageUrl: string;
}

const DATA_PATH = join(__dirname, "data", "shell-plugins.json");

/**
 * Floor for the total plugin count. Upstream only ever grows in practice; a drop
 * below this means the parse broke, not that 1Password deleted half their catalogue.
 * Raise it if the real count climbs well past it — never lower it to make CI pass.
 */
const MIN_PLUGIN_COUNT = 60;

/**
 * Plugins that have existed upstream for years across multiple reorganisations.
 * A correct-looking count with these missing means the parse silently changed shape.
 */
const ANCHOR_SLUGS = ["aws", "github", "terraform", "gitlab", "datadog", "heroku"];

/** Upstream source directory each `pageUrl` must point at. */
const SOURCE_TREE_PREFIX = "https://github.com/1Password/shell-plugins/tree/main/plugins/";

const raw = readFileSync(DATA_PATH, "utf8");
const plugins = JSON.parse(raw) as CuratedPlugin[];

describe("shell-plugins.json integrity", () => {
  it("parses as a non-empty array", () => {
    expect(Array.isArray(plugins)).toBe(true);
    expect(plugins.length).toBeGreaterThan(0);
  });

  it(`contains at least ${MIN_PLUGIN_COUNT} plugins`, () => {
    // Guards the exact regression that motivated these tests: a docs restructure
    // silently produced `[]` and nearly landed a PR deleting every entry.
    expect(plugins.length).toBeGreaterThanOrEqual(MIN_PLUGIN_COUNT);
  });

  it.each(ANCHOR_SLUGS)("includes the long-standing '%s' plugin", (slug) => {
    expect(plugins.map((p) => p.slug)).toContain(slug);
  });

  it("has no duplicate slugs", () => {
    const slugs = plugins.map((p) => p.slug);
    const duplicates = slugs.filter((s, i) => slugs.indexOf(s) !== i);
    expect(duplicates).toEqual([]);
  });
});

describe("shell-plugins.json entry shape", () => {
  it("gives every entry a non-empty name and slug", () => {
    const invalid = plugins.filter(
      (p) => typeof p.name !== "string" || !p.name || typeof p.slug !== "string" || !p.slug,
    );
    expect(invalid).toEqual([]);
  });

  it("uses url-safe lowercase slugs", () => {
    const invalid = plugins.filter((p) => !/^[a-z0-9][a-z0-9-]*$/.test(p.slug));
    expect(invalid.map((p) => p.slug)).toEqual([]);
  });

  it("gives every entry an envVars array", () => {
    const invalid = plugins.filter((p) => !Array.isArray(p.envVars));
    expect(invalid.map((p) => p.slug)).toEqual([]);
  });

  it("only contains well-formed environment variable names", () => {
    // These are written verbatim into the agent's auth.json, so a malformed name
    // would produce an entry the shell can never resolve.
    const invalid = plugins.flatMap((p) =>
      p.envVars.filter((v) => !/^[A-Z][A-Z0-9_]*$/.test(v)).map((v) => `${p.slug}: ${v}`),
    );
    expect(invalid).toEqual([]);
  });

  it("points every pageUrl at the upstream source directory for that slug", () => {
    const invalid = plugins.filter((p) => p.pageUrl !== `${SOURCE_TREE_PREFIX}${p.slug}`);
    expect(invalid.map((p) => p.slug)).toEqual([]);
  });
});

describe("shell-plugins.json primaryEnvVar", () => {
  it("always selects a variable the plugin actually injects", () => {
    // index.ts writes `primaryEnvVar` into auth.json as the recommended default,
    // so one that isn't in envVars would configure a variable the plugin never sets.
    const invalid = plugins.filter(
      (p) => p.primaryEnvVar !== null && !p.envVars.includes(p.primaryEnvVar),
    );
    expect(invalid.map((p) => `${p.slug}: ${p.primaryEnvVar}`)).toEqual([]);
  });

  it("is set whenever the plugin injects any variables", () => {
    const invalid = plugins.filter((p) => p.envVars.length > 0 && p.primaryEnvVar === null);
    expect(invalid.map((p) => p.slug)).toEqual([]);
  });

  it("is null when the plugin injects nothing", () => {
    // Config-file provisioners legitimately inject no env vars; they must not be
    // handed a fabricated primary.
    const invalid = plugins.filter((p) => p.envVars.length === 0 && p.primaryEnvVar !== null);
    expect(invalid.map((p) => p.slug)).toEqual([]);
  });

  it("recommends the credential, not an incidental setting or a niche variant", () => {
    // Pins the ranking in pickPrimaryEnvVar. Each of these regressed under a
    // find-first heuristic: GitHub resolved to GH_ENTERPRISE_TOKEN and Snowflake
    // to SNOWSQL_ACCOUNT purely because they sort earlier.
    const expected: Record<string, string> = {
      aws: "AWS_ACCESS_KEY_ID",
      github: "GH_TOKEN",
      snowflake: "SNOWSQL_PWD",
      postgresql: "PGPASSWORD",
      datadog: "DATADOG_API_KEY",
      gitlab: "GITLAB_TOKEN",
    };

    const actual = Object.fromEntries(
      Object.keys(expected).map((slug) => [
        slug,
        plugins.find((p) => p.slug === slug)?.primaryEnvVar,
      ]),
    );
    expect(actual).toEqual(expected);
  });
});
